"use client";

import React from "react";

export type Finger =
  | "left-pinky"
  | "left-ring"
  | "left-middle"
  | "left-index"
  | "left-thumb"
  | "right-thumb"
  | "right-index"
  | "right-middle"
  | "right-ring"
  | "right-pinky";

export const KEY_MAP: Record<
  string,
  { finger: Finger; hand: "left" | "right" }
> = {
    '1': { finger: 'left-pinky', hand: 'left' }, '!': { finger: 'left-pinky', hand: 'left' },
    'q': { finger: 'left-pinky', hand: 'left' }, 'Q': { finger: 'left-pinky', hand: 'left' },
    'a': { finger: 'left-pinky', hand: 'left' }, 'A': { finger: 'left-pinky', hand: 'left' },
    'z': { finger: 'left-pinky', hand: 'left' }, 'Z': { finger: 'left-pinky', hand: 'left' },
    '`': { finger: 'left-pinky', hand: 'left' }, '~': { finger: 'left-pinky', hand: 'left' },
    
    '2': { finger: 'left-ring', hand: 'left' }, '@': { finger: 'left-ring', hand: 'left' },
    'w': { finger: 'left-ring', hand: 'left' }, 'W': { finger: 'left-ring', hand: 'left' },
    's': { finger: 'left-ring', hand: 'left' }, 'S': { finger: 'left-ring', hand: 'left' },
    'x': { finger: 'left-ring', hand: 'left' }, 'X': { finger: 'left-ring', hand: 'left' },
    
    '3': { finger: 'left-middle', hand: 'left' }, '#': { finger: 'left-middle', hand: 'left' },
    'e': { finger: 'left-middle', hand: 'left' }, 'E': { finger: 'left-middle', hand: 'left' },
    'd': { finger: 'left-middle', hand: 'left' }, 'D': { finger: 'left-middle', hand: 'left' },
    'c': { finger: 'left-middle', hand: 'left' }, 'C': { finger: 'left-middle', hand: 'left' },
    
    '4': { finger: 'left-index', hand: 'left' }, '$': { finger: 'left-index', hand: 'left' },
    'r': { finger: 'left-index', hand: 'left' }, 'R': { finger: 'left-index', hand: 'left' },
    'f': { finger: 'left-index', hand: 'left' }, 'F': { finger: 'left-index', hand: 'left' },
    'v': { finger: 'left-index', hand: 'left' }, 'V': { finger: 'left-index', hand: 'left' },
    
    '5': { finger: 'left-index', hand: 'left' }, '%': { finger: 'left-index', hand: 'left' },
    't': { finger: 'left-index', hand: 'left' }, 'T': { finger: 'left-index', hand: 'left' },
    'g': { finger: 'left-index', hand: 'left' }, 'G': { finger: 'left-index', hand: 'left' },
    'b': { finger: 'left-index', hand: 'left' }, 'B': { finger: 'left-index', hand: 'left' },
    
    '6': { finger: 'right-index', hand: 'right' }, '^': { finger: 'right-index', hand: 'right' },
    'y': { finger: 'right-index', hand: 'right' }, 'Y': { finger: 'right-index', hand: 'right' },
    'h': { finger: 'right-index', hand: 'right' }, 'H': { finger: 'right-index', hand: 'right' },
    'n': { finger: 'right-index', hand: 'right' }, 'N': { finger: 'right-index', hand: 'right' },
    
    '7': { finger: 'right-index', hand: 'right' }, '&': { finger: 'right-index', hand: 'right' },
    'u': { finger: 'right-index', hand: 'right' }, 'U': { finger: 'right-index', hand: 'right' },
    'j': { finger: 'right-index', hand: 'right' }, 'J': { finger: 'right-index', hand: 'right' },
    'm': { finger: 'right-index', hand: 'right' }, 'M': { finger: 'right-index', hand: 'right' },
    
    '8': { finger: 'right-middle', hand: 'right' }, '*': { finger: 'right-middle', hand: 'right' },
    'i': { finger: 'right-middle', hand: 'right' }, 'I': { finger: 'right-middle', hand: 'right' },
    'k': { finger: 'right-middle', hand: 'right' }, 'K': { finger: 'right-middle', hand: 'right' },
    ',': { finger: 'right-middle', hand: 'right' }, '<': { finger: 'right-middle', hand: 'right' },
    
    '9': { finger: 'right-ring', hand: 'right' }, '(': { finger: 'right-ring', hand: 'right' },
    'o': { finger: 'right-ring', hand: 'right' }, 'O': { finger: 'right-ring', hand: 'right' },
    'l': { finger: 'right-ring', hand: 'right' }, 'L': { finger: 'right-ring', hand: 'right' },
    '.': { finger: 'right-ring', hand: 'right' }, '>': { finger: 'right-ring', hand: 'right' },
    
    '0': { finger: 'right-pinky', hand: 'right' }, ')': { finger: 'right-pinky', hand: 'right' },
    'p': { finger: 'right-pinky', hand: 'right' }, 'P': { finger: 'right-pinky', hand: 'right' },
    ';': { finger: 'right-pinky', hand: 'right' }, ':': { finger: 'right-pinky', hand: 'right' },
    '/': { finger: 'right-pinky', hand: 'right' }, '?': { finger: 'right-pinky', hand: 'right' },
    '-': { finger: 'right-pinky', hand: 'right' }, '_': { finger: 'right-pinky', hand: 'right' },
    '=': { finger: 'right-pinky', hand: 'right' }, '+': { finger: 'right-pinky', hand: 'right' },
    '[': { finger: 'right-pinky', hand: 'right' }, '{': { finger: 'right-pinky', hand: 'right' },
    ']': { finger: 'right-pinky', hand: 'right' }, '}': { finger: 'right-pinky', hand: 'right' },
    "'": { finger: 'right-pinky', hand: 'right' }, '"': { finger: 'right-pinky', hand: 'right' },
    '\\': { finger: 'right-pinky', hand: 'right' }, '|': { finger: 'right-pinky', hand: 'right' },
    
    ' ': { finger: 'right-thumb', hand: 'right' },
};


export const ROMAJI_MAP: Record<string, string[]> = {
  あ: ["a"],
  い: ["i"],
  う: ["u"],
  え: ["e"],
  お: ["o"],
  か: ["ka"],
  き: ["ki"],
  く: ["ku"],
  け: ["ke"],
  こ: ["ko"],
  さ: ["sa"],
  し: ["si", "shi"],
  す: ["su"],
  せ: ["se"],
  そ: ["so"],
  た: ["ta"],
  ち: ["ti", "chi"],
  つ: ["tu", "tsu"],
  て: ["te"],
  と: ["to"],
  な: ["na"],
  に: ["ni"],
  ぬ: ["nu"],
  ね: ["ne"],
  の: ["no"],
  は: ["ha"],
  ひ: ["hi"],
  ふ: ["hu", "fu"],
  へ: ["he"],
  ほ: ["ho"],
  ま: ["ma"],
  み: ["mi"],
  む: ["mu"],
  め: ["me"],
  も: ["mo"],
  や: ["ya"],
  ゆ: ["yu"],
  よ: ["yo"],
  ら: ["ra"],
  り: ["ri"],
  る: ["ru"],
  れ: ["re"],
  ろ: ["ro"],
  わ: ["wa"],
  を: ["wo"],
  ん: ["nn", "n"],
  が: ["ga"],
  ぎ: ["gi"],
  ぐ: ["gu"],
  げ: ["ge"],
  ご: ["go"],
  ざ: ["za"],
  じ: ["zi", "ji"],
  ず: ["zu"],
  ぜ: ["ze"],
  ぞ: ["zo"],
  だ: ["da"],
  ぢ: ["di"],
  づ: ["du"],
  で: ["de"],
  ど: ["do"],
  ば: ["ba"],
  び: ["bi"],
  ぶ: ["bu"],
  べ: ["be"],
  ぼ: ["bo"],
  ぱ: ["pa"],
  ぴ: ["pi"],
  ぷ: ["pu"],
  ぺ: ["pe"],
  ぽ: ["po"],
  きゃ: ["kya"],
  きゅ: ["kyu"],
  きょ: ["kyo"],
  しゃ: ["sya", "sha"],
  しゅ: ["syu", "shu"],
  しょ: ["syo", "sho"],
  ちゃ: ["tya", "cha"],
  ちゅ: ["tyu", "chu"],
  ちょ: ["tyo", "cho"],
  にゃ: ["nya"],
  にゅ: ["nyu"],
  にょ: ["nyo"],
  ひゃ: ["hya"],
  ひゅ: ["hyu"],
  ひょ: ["hyo"],
  みゃ: ["mya"],
  みゅ: ["myu"],
  みょ: ["myo"],
  りゃ: ["rya"],
  りゅ: ["ryu"],
  りょ: ["ryo"],
  ぎゃ: ["gya"],
  ぎゅ: ["gyu"],
  ぎょ: ["gyo"],
  じゃ: ["zya", "ja"],
  じゅ: ["zyu", "ju"],
  じょ: ["zyo", "jo"],
  びゃ: ["bya"],
  びゅ: ["byu"],
  びょ: ["byo"],
  ぴゃ: ["pya"],
  ぴゅ: ["pyu"],
  ぴょ: ["pyo"],
  っ: ["ltu", "ltsu", "xtu"], 
  ー: ["-"],
};
